name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Lint code
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build library
        run: cargo build --release
